### ISSUE TITLE
can't build on osx

### ISSUE THREAD

**Issue by namdroid** [cernekee/ics-openconnect#13]
hi, 
i get 

readlink: illegal option -- f

while running make

**Comment by namdroid** [comment]
i've replaced readlink with grealink in sh script, then it works, but now i get:
...
../../sources/stoken-0.81/src/sdtid.c: In function 'parse_date':
../../sources/stoken-0.81/src/sdtid.c:837:2: error: implicit declaration of function 'timegm' [-Werror=implicit-function-declaration]

**Comment by namdroid** [comment]
compile iwth ndk-r10e i get:
...
compiling static library
lz4.c: In function 'LZ4_slideInputBuffer':
lz4.c:1324:33: warning: cast increases required alignment of target type [-Wcast-align]
     int dictSize = LZ4_saveDict((LZ4_stream_t*)ctx, (char*)ctx->bufferStart, 64 KB);
                                 ^
lz4hc.c: In function 'LZ4_compressHC_continue_generic':
lz4hc.c:645:24: warning: cast increases required alignment of target type [-Wcast-align]
         LZ4_loadDictHC((LZ4_streamHC_t*)ctxPtr, (const char*)(ctxPtr->end) - dictSize, (int)dictSize);
                        ^
compiling dynamic library 1.5.0
arm-linux-androideabi-gcc: error: /usr/lib/liblz4.1.dylib: No such file or directory
arm-linux-androideabi-gcc: error: 1: No such file or directory
arm-linux-androideabi-gcc: error: 1.5.0: No such file or directory
arm-linux-androideabi-gcc: error: unrecognized command line option '-install_name'
arm-linux-androideabi-gcc: error: unrecognized command line option '-compatibility_version'
arm-linux-androideabi-gcc: error: unrecognized command line option '-current_version'
make[2]: *** [liblz4] Error 1

..

any idea ?

**Comment by namdroid** [comment]
ok, i switched to debian 8 and android-ndk-e10e and it works.

**Comment by schemacs** [comment]
android-ndk-e10d also works on Ubuntu 16.04.

**Comment by cernekee** [comment]
Added an experimental option to download prebuilt native libraries, so it should be possible to hack on the app using OSX or Windows.  Let me know how it works.
